const products = [
  ['Bases de glicerina', 'Blanca · 1 kg', 'S/ 26.00', 'Bases', '🧼', 'Base blanca'],
  ['Bases de glicerina', 'Blanca · 5 kg', 'S/ 25.00 c/u', 'Bases', '🧼', 'Base blanca'],
  ['Bases de glicerina', 'Blanca · 10 kg', 'S/ 24.50 c/u', 'Bases', '🧼', 'Base blanca'],
  ['Bases de glicerina', 'Ámbar · 1 kg', 'S/ 26.00', 'Bases', '🧼', 'Base ámbar'],
  ['Bases de glicerina', 'Ámbar · 5 kg', 'S/ 25.00 c/u', 'Bases', '🧼', 'Base ámbar'],
  ['Bases de glicerina', 'Ámbar · 10 kg', 'S/ 24.50 c/u', 'Bases', '🧼', 'Base ámbar'],
  ['Bases de glicerina', 'Transparente cristal · 1 kg', 'S/ 29.00', 'Bases', '✨', 'Base cristal'],
  ['Bases de glicerina', 'Transparente cristal · 5 kg', 'S/ 28.00 c/u', 'Bases', '✨', 'Base cristal'],
  ['Bases de glicerina', 'Transparente cristal · 10 kg', 'S/ 27.50 c/u', 'Bases', '✨', 'Base cristal'],
  ...['Coco','Bambú','Maracuyá','Naranja','Eucalipto','Manzanilla','Rosas','Chocolate','Tutifruti','Jazmín','Café','Limón','Lavanda','Chicle','Hierba Luisa','Manzana','Fresas','Almendras','Bebé','Vainilla','Brisa Marina','Rosa Búlgara','Avena','Calvin Klein','Manzana Canela','Té Verde','Paco Rabanne','Talco BB','Miel','Sábila','Uva','Sándalo','Frutos Rojos','Leche','Pachulí','Cherry','Algodón','Violeta','Canela','Cereza','Channel','Durazno','Frambuesa','Gardenia','Mandarina','Mango','Menta','Mil Flores','Orquídea','Piña','Ruda','Sandía','Romero','Avena y Miel'].map(n=>['Fragancia '+n,'20 ml','S/ 18.00','Fragancias','🌸',n]),
  ...['Melissa','Lavanda','Árbol de té','Limón','Menta','Eucalipto','Bergamota','Clavo de olor','Romero','Citronela','Rosas','Ylang Ylang','Mandarina','Jazmín','Naranja','Cyprees','Anís'].map(n=>['Aceite esencial '+n,'15 ml','S/ 28.00','Aceites esenciales','🌿',n]),
  ...['Almendras','Semilla de uva','Argán','Rosas','Castaña','Coco','Eucalipto','Maracuyá','Rosa mosqueta','Aguaje','Copaiba','Chía','Girasol','Oliva','Jojoba','Ricino'].map(n=>['Aceite vegetal '+n,'30 ml','S/ 28.00','Aceites vegetales','🥥',n]),
  ['Vitamina E', '10 ml', 'S/ 18.00', 'Complementos', '💧', 'Vitamina E'],
  ['Conservante Procidé', '10 ml', 'S/ 15.00', 'Complementos', '🧪', 'Conservante'],
  ['Vitamina E', '30 ml', 'S/ 36.00', 'Complementos', '🧪', 'Conservante'],
  ...['Blanca','Verde','Roja','Rosa'].map(n=>['Arcilla '+n,'50 g / 100 g','S/ 11.00 / S/ 23.00','Arcillas','🪨',n]),
  ...['Zanahoria','Menta','Áloe vera','Lavanda','Uva','Avena','Té verde','Manzanilla','Caléndula','Orégano','Hamamelis','Rosas'].map(n=>['Extracto natural de '+n,'30 ml','S/ 28.00','Extractos naturales','🌱',n]),
  ...['Carbón','Polvo de arroz','Manzanilla','Avena orgánica','Cacao','Coco','Romero','Lúcuma','Eucalipto','Almendras','Limón','Flor de jamaica','Ruda','Ortiga','Neem','Flor de caléndula','Lavanda','Menta','Naranja','Sangre de grado','Sábila','Camu camu','Beterraga','Chía','Hierba luisa','Manzanilla','Fenogreco','Jengibre','Moringa','Semillas de girasol','Muña'].map(n=>['Planta pulverizada · '+n,'50 g / 100 g','S/ 11.00 / S/ 23.00','Plantas pulverizadas','🌿',n]),
  ...['Rojo','Azul','Amarillo','Verde'].map(n=>['Colorante líquido migrante · '+n,'10 ml','S/ 10.00','Colorantes','🎨',n]),
  ...['Rojo','Azul','Amarillo','Verde','Negro','Marrón','Morado','Rosa','Naranja'].map(n=>['Colorante líquido no migrante · '+n,'10 ml','S/ 13.50 c/u','Colorantes','🎨',n]),
  ...['Azul','Amarillo','Verde','Negro','Marrón','Morado','Dorado','Naranja'].map(n=>['Mica grado cosmético · '+n,'10 g','S/ 10.50 c/u','Micas','✨',n]),
  ['Cocobetaina', '250 ml', 'S/ 15.00', 'Espumantes', '🫧', 'Cocobetaina'],
  ['Cocobetaina', '1/2 litro', 'S/ 26.00', 'Espumantes', '🫧', 'Cocobetaina'],
  ['Cocobetaina', '1 litro', 'S/ 50.00', 'Espumantes', '🫧', 'Cocobetaina'],
  ['Glicerina líquida', '250 ml', 'S/ 15.00', 'Espumantes', '💧', 'Glicerina líquida'],
  ['Vaselina líquida', '250 ml', 'S/ 15.00', 'Espumantes', '💧', 'Vaselina líquida'],
  ['Fijador de aroma', '10 ml', 'S/ 15.00', 'Espumantes', '🧴', 'Fijador'],
  ['Manteca de cacao', '35 g', 'S/ 18.00', 'Aditivos', '🧈', 'Manteca de cacao'],
  ['Manteca de karité', '35 g', 'S/ 16.00', 'Aditivos', '🧈', 'Manteca de karité'],
  ['Manteca de karité', '65 g', 'S/ 20.00', 'Aditivos', '🧈', 'Manteca de karité'],
  ['Balanza gramera', 'Unidad', 'S/ 20.00', 'Implementos', '⚖️', 'Balanza'],
  ['Juego de cortador para jabones', 'Juego', 'S/ 85.00', 'Implementos', '🔪', 'Cortador'],
  ['Termómetro', 'Unidad', 'S/ 20.00', 'Implementos', '🌡️', 'Termómetro'],
  ['Cortador de bases', 'Unidad', 'S/ 18.00', 'Implementos', '🧰', 'Cortador'],
  ['Bolsa de organza N.º 1', '7 × 9 cm · unidad', 'S/ 2.00', 'Bolsas de organza', '🎁', 'Organza 1'],
  ['Bolsa de organza N.º 1', '12 unidades', 'S/ 18.00', 'Bolsas de organza', '🎁', 'Organza 1'],
  ['Bolsa de organza N.º 1', '25 unidades', 'S/ 30.00', 'Bolsas de organza', '🎁', 'Organza 1'],
  ['Bolsa de organza N.º 2', '9 × 12 cm · unidad', 'S/ 2.00', 'Bolsas de organza', '🎁', 'Organza 2'],
  ['Bolsa de organza N.º 2', '12 unidades', 'S/ 18.00', 'Bolsas de organza', '🎁', 'Organza 2'],
  ['Bolsa de organza N.º 2', '25 unidades', 'S/ 30.00', 'Bolsas de organza', '🎁', 'Organza 2'],
  ['Bolsa de organza N.º 3', '10 × 16 cm · unidad', 'S/ 2.00', 'Bolsas de organza', '🎁', 'Organza 3'],
  ['Bolsa de organza N.º 3', '12 unidades', 'S/ 18.00', 'Bolsas de organza', '🎁', 'Organza 3'],
  ['Bolsa de organza N.º 3', '25 unidades', 'S/ 30.00', 'Bolsas de organza', '🎁', 'Organza 3'],
  ['Parafina Premium', '1 kg', 'S/ 38.00', 'Parafinas', '🕯️', 'Parafina Premium'],
  ['Parafina en gel', '1 kg', 'S/ 68.00', 'Parafinas', '🕯️', 'Parafina en gel'],
  ['Parafina en gel', '1/2 kilo', 'S/ 38.00', 'Parafinas', '🕯️', 'Parafina en gel 1/2 kilo'],
  ['Molde 3D Virgen Guadalupe', '60 g', 'S/ 35.00', 'Moldes 3D', '🕯️', 'Virgen Guadalupe'],
  ['Molde 3D Osito Sentado 01', '30 g', 'S/ 15.00', 'Moldes 3D', '🧸', 'Osito 01'],
  ['Molde 3D Osito Sentado 02', '20 g', 'S/ 20.00', 'Moldes 3D', '🧸', 'Osito 02'],
  ['Molde 3D Osito Sentado 03', 'Unidad', 'S/ 20.00', 'Moldes 3D', '🧸', 'Osito 03'],
  ['Molde 3D Osito Sentado 04', '20 g', 'S/ 20.00', 'Moldes 3D', '🧸', 'Osito 04'],
  ['Molde 3D Osito Sentado 05', '20 g', 'S/ 20.00', 'Moldes 3D', '🧸', 'Osito 05'],
  ['Molde 3D Osito Corazón 13', 'Unidad', 'S/ 25.00', 'Moldes 3D', '🧸', 'Osito Corazón 13'],
  ['Molde 3D Osito Winni Pooh', 'Unidad', 'S/ 32.00', 'Moldes 3D', '🧸', 'Winni Pooh'],
  ['Molde 3D Osito', 'Unidad', 'S/ 13.00', 'Moldes 3D', '🧸', 'Osito'],
  ['Molde 3D Osito Kawaii', 'Unidad', 'S/ 20.00 (Agotado)', 'Moldes 3D', '🧸', 'Osito Kawaii'],
  ['Molde 3D Osito Calabaza', 'Unidad', 'S/ 22.00', 'Moldes 3D', '🧸', 'Osito Calabaza'],
  ['Molde 3D Osito Rosas', 'Unidad', 'S/ 20.00', 'Moldes 3D', '🧸', 'Osito Rosas'],
  ['Molde 3D Elefante 01', '45 g', 'S/ 20.00', 'Moldes 3D', '🐘', 'Elefante 01'],
  ['Molde 3D Elefante 03', '45 g', 'S/ 28.50', 'Moldes 3D', '🐘', 'Elefante 03'],
  ['Molde 3D Elefante 04', 'Unidad', 'S/ 45.00', 'Moldes 3D', '🐘', 'Elefante 04'],
  ['Molde 3D Elefante 05', 'Unidad', 'S/ 45.00', 'Moldes 3D', '🐘', 'Elefante 05'],
  ['Molde 3D Leoncito', '35 g', 'S/ 20.00', 'Moldes 3D', '🦁', 'Leoncito'],
  ['Molde 3D Jirafa', '45 g', 'S/ 28.00', 'Moldes 3D', '🦒', 'Jirafa'],
  ['Molde 3D Llamita', 'Unidad', 'S/ 15.00', 'Moldes 3D', '🦙', 'Llamita'],
  ['Molde 3D Mini Oveja', 'Unidad', 'S/ 10.00', 'Moldes 3D', '🐑', 'Mini Oveja'],
  ['Molde 3D Gatito', 'Unidad', 'S/ 18.00', 'Moldes 3D', '🐱', 'Gatito'],
  ['Molde 3D Oveja Kawaii', '30 g', 'S/ 24.00', 'Moldes 3D', '🐑', 'Oveja Kawaii'],
  ['Molde 3D Búho', 'Unidad', 'S/ 20.00', 'Moldes 3D', '🦉', 'Búho'],
  ['Molde 3D Conejita', 'Unidad', 'S/ 20.00', 'Moldes 3D', '🐰', 'Conejita'],
  ['Molde 3D Chanchito 01', 'Unidad', 'S/ 22.00', 'Moldes 3D', '🐷', 'Chanchito 01'],
  ['Molde 3D Chanchito 03', 'Unidad', 'S/ 22.00', 'Moldes 3D', '🐷', 'Chanchito 03'],
  ['Molde 3D Vaca', 'Unidad', 'S/ 23.00', 'Moldes 3D', '🐮', 'Vaca'],
  ['Molde 3D Bebito 01', 'Unidad', 'S/ 35.00', 'Moldes 3D', '👶', 'Bebito 01'],
  ['Molde 3D Bebito 02', 'Unidad', 'S/ 45.00', 'Moldes 3D', '👶', 'Bebito 02'],
  ['Molde 3D Bebito 03', 'Unidad', 'S/ 45.00', 'Moldes 3D', '👶', 'Bebito 03'],
  ['Molde 3D Bebito 04', 'Unidad', 'S/ 24.00', 'Moldes 3D', '👶', 'Bebito 04'],
  ['Molde 3D Molde Angelito', '38 g', 'S/ 20.00', 'Moldes 3D', '👼', 'Angelito'],
  ['Molde 3D Angelitos', 'Unidad', 'S/ 28.00', 'Moldes 3D', '👼', 'Angelitos'],
  ['Molde 3D Angelito Pequeño', 'Unidad', 'S/ 15.00', 'Moldes 3D', '👼', 'Angelito Pequeño'],
  ['Molde 3D Angelitos Grandes', 'Unidad', 'S/ 32.00 c/u', 'Moldes 3D', '👼', 'Angelitos Grandes'],
  ['Molde 3D Arándano', 'Unidad', 'S/ 20.00', 'Moldes 3D', '🫐', 'Arándano'],
  ['Molde 3D Frambuesa', 'Unidad', 'S/ 20.00', 'Moldes 3D', '🍓', 'Frambuesa'],
  ['Molde 3D Margarita', '18 g', 'S/ 20.00', 'Moldes 3D', '🌼', 'Margarita'],
  ['Molde 3D Girasol', '18 g', 'S/ 20.00', 'Moldes 3D', '🌻', 'Girasol'],
  ['Molde 3D Peonía Pequeña', 'Unidad', 'S/ 28.00', 'Moldes 3D', '🌸', 'Peonía Pequeña'],
  ['Molde 3D Flor', 'Unidad', 'S/ 20.00', 'Moldes 3D', '🌸', 'Flor'],
  ['Molde 3D Flor Navideña', 'Unidad', 'S/ 15.00', 'Moldes 3D', '🌺', 'Flor Navideña'],
  ['Molde 3D Mini Flores de Cerezo', 'Unidad', 'S/ 15.00', 'Moldes 3D', '🌸', 'Flores de Cerezo'],
  ['Molde 3D Corazón Tejido Pequeño', 'Unidad', 'S/ 16.00', 'Moldes 3D', '💖', 'Corazón Tejido'],
  ['Molde 3D Virgencita 01', 'Unidad', 'S/ 20.00', 'Moldes 3D', '🕯️', 'Virgencita 01'],
  ['Molde 3D Virgencita 02', 'Unidad', 'S/ 20.00', 'Moldes 3D', '🕯️', 'Virgencita 02'],
  ['Molde 3D Cubo Pequeño', '45 g', 'S/ 25.00', 'Moldes 3D', '🧊', 'Cubo Pequeño'],
  ['Molde 3D Burbuja x6', '120 g', 'S/ 32.00', 'Moldes 3D', '🫧', 'Burbuja x6'],
  ['Molde 3D Burbuja Corazón', '140 g', 'S/ 35.00', 'Moldes 3D', '🫧', 'Burbuja Corazón'],
  ['Molde 3D Compromiso', 'Unidad', 'S/ 26.00', 'Moldes 3D', '💍', 'Compromiso'],
  ['Molde 3D Flor (18 soles)', 'Unidad', 'S/ 18.00', 'Moldes 3D', '🌸', 'Flor (18)'],
  ['Molde 3D Corazón Floral', 'Unidad', 'S/ 18.00', 'Moldes 3D', '💖', 'Corazón Floral'],
  ['Molde 3D Flor (60g)', '60 g', 'S/ 20.00', 'Moldes 3D', '🌸', 'Flor (60g)'],
  ['Molde 3D Virgen 3D', 'Unidad', 'S/ 45.00', 'Moldes 3D', '🕯️', 'Virgen 3D'],
  ['Molde 3D Flor (48g)', '48 g', 'S/ 20.00 (Agotado)', 'Moldes 3D', '🌸', 'Flor (48g)'],
  ['Molde 3D Cuerpo de Mujer', '90 g', 'S/ 28.00', 'Moldes 3D', '🧍‍♀️', 'Cuerpo de Mujer'],
  ['Molde 3D Angel Mujer', '80 g', 'S/ 25.00 (Agotado)', 'Moldes 3D', '👼', 'Angel Mujer'],
  ['Molde 3D Cruz', 'Unidad', 'S/ 22.00', 'Moldes 3D', '✝️', 'Cruz'],
  ['Molde 3D Mini Rosas', 'Unidad', 'S/ 15.00 (Agotado)', 'Moldes 3D', '🌹', 'Mini Rosas'],
  ['Molde 3D Mini Hojas de Acebo', 'Unidad', 'S/ 15.00', 'Moldes 3D', '🌿', 'Hojas de Acebo'],
  ['Molde 3D Diosa', 'Unidad', 'S/ 20.00', 'Moldes 3D', '🗽', 'Diosa'],
  ['Molde 3D Piecito con Mano', 'Unidad', 'S/ 28.00', 'Moldes 3D', '👣', 'Piecito con Mano'],
  ['Molde 3D Madre y BB', 'Unidad', 'S/ 28.00', 'Moldes 3D', '👩‍👦', 'Madre y BB'],
  ['Molde 3D Madre con Hija', 'Unidad', 'S/ 27.00 (Agotada)', 'Moldes 3D', '👩‍👧', 'Madre con Hija'],
  ['Molde 3D Mama y Bebe 2', 'Unidad', 'S/ 26.00', 'Moldes 3D', '👩‍👦', 'Mama y Bebe 2'],
  ['Molde 3D Rosa Espinal', 'Unidad', 'S/ 20.00', 'Moldes 3D', '🌹', 'Rosa Espinal'],
  ['Molde 3D Madre e Hijo', 'Unidad', 'S/ 18.00 / S/ 28.00', 'Moldes 3D', '👩‍👦', 'Madre e Hijo'],
  ['Molde 3D Buda 3D', 'Unidad', 'S/ 20.00', 'Moldes 3D', '🧘', 'Buda 3D'],
  ['Molde 3D Suculenta', 'Unidad', 'S/ 28.00 (Agotado)', 'Moldes 3D', '🪴', 'Suculenta'],
  ['Molde 3D Flor 05', 'Unidad', 'S/ 23.00 (Agotado)', 'Moldes 3D', '🌸', 'Flor 05'],
  ['Molde 3D Flor Cerámico', 'Unidad', 'S/ 18.00', 'Moldes 3D', '🌸', 'Flor Cerámico'],
  ['Molde 3D Conejito Cerámico', 'Unidad', 'S/ 24.00', 'Moldes 3D', '🐰', 'Conejito Cerámico'],
  ['Molde 3D Niña Graduada', '75 g', 'S/ 45.00', 'Moldes 3D', '🎓', 'Niña Graduada'],
  ['Molde 3D Niño Graduado', '75 g', 'S/ 50.00', 'Moldes 3D', '🎓', 'Niño Graduado'],
  ['Molde 3D Pastorcita', 'Unidad', 'S/ 32.00', 'Moldes 3D', '🐑', 'Pastorcita'],
  ['Molde 3D Niña con Ramo', 'Unidad', 'S/ 28.00', 'Moldes 3D', '💐', 'Niña con Ramo'],
  ['Molde 3D Taza Macetero', 'Unidad', 'S/ 25.00', 'Moldes 3D', '☕', 'Taza Macetero'],
  ['Molde 3D Corazón', 'Unidad', 'S/ 20.00', 'Moldes 3D', '❤️', 'Corazón'],
  ['Molde 3D Familia Navideña', 'Unidad', 'S/ 45.00', 'Moldes 3D', '🎄', 'Familia Navideña'],
  ['Molde 3D Santa Claus', 'Unidad', 'S/ 37.00', 'Moldes 3D', '🎅', 'Santa Claus'],
  ['Molde 3D Molde Deseo 2026', 'Unidad', 'S/ 25.00 c/u', 'Moldes 3D', '✨', 'Deseo 2026'],
  ['Molde 3D Árbol Navideño', '65 g', 'S/ 25.00', 'Moldes 3D', '🎄', 'Árbol Navideño'],
  ['Molde 3D Molde Navideño', 'Unidad', 'S/ 15.00 c/u', 'Moldes 3D', '🎄', 'Navideño'],
  ['Molde 3D Árbol Navideño 03', 'Unidad', 'S/ 48.00', 'Moldes 3D', '🎄', 'Árbol Navideño 03'],
  ['Molde 3D Árbol Pequeño 01', 'Unidad', 'S/ 15.00', 'Moldes 3D', '🎄', 'Árbol Peq 01'],
  ['Molde 3D Árbol Geométrico', 'Unidad', 'S/ 15.00', 'Moldes 3D', '🎄', 'Árbol Geom'],
  ['Molde 3D Árbol Pequeño 02', 'Unidad', 'S/ 15.00', 'Moldes 3D', '🎄', 'Árbol Peq 02'],
  ['Molde 3D Árbol Geométrico Grande', 'Unidad', 'S/ 20.00', 'Moldes 3D', '🎄', 'Árbol Geom Gde'],
  ['Molde 3D Deseo x4', 'Unidad', 'S/ 65.00', 'Moldes 3D', '✨', 'Deseo x4'],
  ['Molde 3D Árbol Pequeño', 'Unidad', 'S/ 15.00', 'Moldes 3D', '🎄', 'Árbol Pequeño'],
  ['Molde 3D Osito Sentado 08', 'Unidad', 'S/ 20.00 (Agotado)', 'Moldes 3D', '🧸', 'Osito 08'],
  ['Molde 2D Rectangular x6', '90 g', 'S/ 20.00', 'Moldes 2D', '🧼', 'Rectangular x6'],
  ['Molde 2D Rectangular x9', '140 g', 'S/ 24.00', 'Moldes 2D', '🧼', 'Rectangular x9'],
  ['Molde 2D Cuadrado x6', 'Unidad', 'S/ 20.00', 'Moldes 2D', '🧼', 'Cuadrado x6'],
  ['Molde 2D Rectangular x4 con Diseño', 'Unidad', 'S/ 20.00', 'Moldes 2D', '🧼', 'Rect x4 Diseño'],
  ['Molde 2D Rectangular x6 con Diseño', '100 g', 'S/ 22.00', 'Moldes 2D', '🧼', 'Rect x6 Diseño'],
  ['Molde 2D Ovalado x6', '100 g', 'S/ 22.00', 'Moldes 2D', '🧼', 'Ovalado x6'],
  ['Molde 2D Oxagonal x6', '80 g', 'S/ 22.00', 'Moldes 2D', '🧼', 'Oxagonal x6'],
  ['Molde 2D Árbol de Vida', '120 g', 'S/ 23.00', 'Moldes 2D', '🌳', 'Árbol de Vida'],
  ['Molde 2D Angel x4', '70 g', 'S/ 22.00', 'Moldes 2D', '👼', 'Angel x4'],
  ['Molde 2D Ovalado x6 (90g)', '90 g', 'S/ 20.00', 'Moldes 2D', '🧼', 'Ovalado x6 90g'],
  ['Molde 2D Ovalados x4', '100 g', 'S/ 20.00', 'Moldes 2D', '🧼', 'Ovalados x4'],
  ['Molde 2D Ovalados Pequeños', '15 g', 'S/ 20.00', 'Moldes 2D', '🧼', 'Ovalados Pequeños'],
  ['Molde 2D Panal de Abeja', 'Unidad', 'S/ 18.00', 'Moldes 2D', '🍯', 'Panal de Abeja'],
  ['Molde 2D Figuras Variadas x6', 'Unidad', 'S/ 21.00', 'Moldes 2D', '🟢', 'Figuras Variadas'],
  ['Molde 2D Copo de Nieve', 'Unidad', 'S/ 19.00', 'Moldes 2D', '❄️', 'Copo de Nieve'],
  ['Molde 2D Figuras x4', '80 g', 'S/ 23.00 (Agotado)', 'Moldes 2D', '🟢', 'Figuras x4'],
  ['Molde 2D Marino Variado', 'Unidad', 'S/ 20.00', 'Moldes 2D', '🌊', 'Marino Variado'],
  ['Molde 2D Rectangulares Pequeños', '15 g', 'S/ 19.00', 'Moldes 2D', '🧼', 'Rectangulares Peq'],
  ['Molde 2D Masajeador Ovalado', '120 g', 'S/ 22.00', 'Moldes 2D', '💆', 'Masajeador Ovalado'],
  ['Molde 2D Masajeador Redondo', '80 g', 'S/ 20.00', 'Moldes 2D', '💆', 'Masajeador Redondo'],
  ['Molde 2D Masajeador Rectangular', '100 g', 'S/ 20.00', 'Moldes 2D', '💆', 'Masajeador Rectangular'],
  ['Molde 2D Rosas x6', '80 g', 'S/ 19.00', 'Moldes 2D', '🌹', 'Rosas 6'],
  ['Molde 2D Marino Variado (80g)', '80 g', 'S/ 19.00', 'Moldes 2D', '🌊', 'Marino 80g'],
  ['Molde 2D Flores Redondas', '90 g', 'S/ 19.50', 'Moldes 2D', '🌸', 'Flores Redondas'],
  ['Molde 2D Flores x6', 'Unidad', 'S/ 19.00', 'Moldes 2D', '🌸', 'Flores x6'],
  ['Molde 2D Flores Variadas', '80 g', 'S/ 19.00', 'Moldes 2D', '🌸', 'Flores Variadas'],
  ['Molde 2D Flores k6', 'Unidad', 'S/ 19.00 (Agotado)', 'Moldes 2D', '🌸', 'Flores k6'],
  ['Molde 2D Rosas x6 (Sin peso)', 'Unidad', 'S/ 19.00', 'Moldes 2D', '🌹', 'Rosas x6'],
  ['Molde 2D Rosa y Tulipán x6', '80 g', 'S/ 19.00', 'Moldes 2D', '🌷', 'Rosa y Tulipán'],
  ['Molde 2D Molde Hojas', 'Unidad', 'S/ 22.00', 'Moldes 2D', '🍃', 'Molde Hojas'],
  ['Molde 2D Corazones Rosado', 'Unidad', 'S/ 19.00', 'Moldes 2D', '❤️', 'Corazones Rosado'],
  ['Molde 2D Emojis Boquita', 'Unidad', 'S/ 18.00', 'Moldes 2D', '💋', 'Emojis Boquita'],
  ['Molde 2D Corazones Ones x6', 'Unidad', 'S/ 19.00', 'Moldes 2D', '❤️', 'Corazones Ones'],
  ['Molde 2D Corazones 2', 'Unidad', 'S/ 19.00', 'Moldes 2D', '❤️', 'Corazones 2'],
  ['Molde 2D Corazones con Lazo', 'Unidad', 'S/ 18.00', 'Moldes 2D', '💝', 'Corazones Lazo'],
  ['Molde 2D Corazones x6', 'Unidad', 'S/ 20.00', 'Moldes 2D', '❤️', 'Corazones x6'],
  ['Molde 2D Corazones 3', 'Unidad', 'S/ 19.00 (Agotado)', 'Moldes 2D', '❤️', 'Corazones 3'],
  ['Molde 2D Corazón Diamante', 'Unidad', 'S/ 20.00', 'Moldes 2D', '💎', 'Corazón Diamante'],
  ['Molde 2D Piñas Pequeñas', 'Unidad', 'S/ 14.00', 'Moldes 2D', '🍍', 'Piñas Pequeñas'],
  ['Molde 2D Tulipanes', '60 g', 'S/ 20.00', 'Moldes 2D', '🌷', 'Tulipanes'],
  ['Molde 2D Manzana', '65 g', 'S/ 19.00', 'Moldes 2D', '🍎', 'Manzana'],
  ['Molde 2D Concha x4', 'Unidad', 'S/ 15.00', 'Moldes 2D', '🐚', 'Concha x4'],
  ['Molde 2D Letras y Números', '10 g', 'S/ 19.50', 'Moldes 2D', '🔠', 'Letras y Números'],
  ['Molde 2D Baby Shower', '80 g', 'S/ 19.00', 'Moldes 2D', '🍼', 'Baby Shower'],
  ['Molde 2D Cruces', 'Unidad', 'S/ 19.00', 'Moldes 2D', '✝️', 'Cruces'],
  ['Molde 2D Trofeos', '25 g', 'S/ 19.00', 'Moldes 2D', '🏆', 'Trofeos'],
  ['Molde 2D Donas x6', 'Unidad', 'S/ 17.00', 'Moldes 2D', '🍩', 'Donas x6'],
  ['Molde 2D Frutas Pequeñas', 'Unidad', 'S/ 14.00', 'Moldes 2D', '🍒', 'Frutas Pequeñas'],
  ['Molde 2D Corazón Diamante (15 soles)', 'Unidad', 'S/ 15.00', 'Moldes 2D', '💎', 'Corazón Diamante 15'],
  ['Molde 2D Huellitas', 'Unidad', 'S/ 19.00', 'Moldes 2D', '🐾', 'Huellitas'],
  ['Molde 2D Hello Kitty', 'Unidad', 'S/ 20.00', 'Moldes 2D', '🐱', 'Hello Kitty'],
  ['Molde 2D Molde Osito x6', 'Unidad', 'S/ 20.00', 'Moldes 2D', '🧸', 'Osito x6'],
  ['Molde 2D Safari', '85 g', 'S/ 19.00', 'Moldes 2D', '🦁', 'Safari'],
  ['Molde 2D Capibara', 'Unidad', 'S/ 20.00', 'Moldes 2D', '🦦', 'Capibara'],
  ['Molde 2D Insectos', '85 g', 'S/ 20.00', 'Moldes 2D', '🐞', 'Insectos'],
  ['Molde 2D Miembro', '35 g', 'S/ 18.00', 'Moldes 2D', '🍆', 'Miembro'],
  ['Molde 2D Dinosaurios', 'Unidad', 'S/ 21.00', 'Moldes 2D', '🦖', 'Dinosaurios'],
  ['Molde 2D Dinosaurios (22 soles)', 'Unidad', 'S/ 22.00 (Agotado)', 'Moldes 2D', '🦖', 'Dinosaurios 22'],
  ['Molde 2D Abejas Variadas', 'Unidad', 'S/ 22.00', 'Moldes 2D', '🐝', 'Abejas Variadas'],
  ['Molde 2D Halloween', 'Unidad', 'S/ 20.00', 'Moldes 2D', '🎃', 'Halloween'],
  ['Molde 2D Calabazas', '15 g', 'S/ 20.00', 'Moldes 2D', '🎃', 'Calabazas'],
  ['Molde 2D Fantasmas', '15 g', 'S/ 20.00', 'Moldes 2D', '👻', 'Fantasmas'],
  ['Molde 2D Calaberas', 'Unidad', 'S/ 18.00', 'Moldes 2D', '💀', 'Calaberas'],
  ['Molde 2D Árbol de Navidad', 'Unidad', 'S/ 19.50 (Agotado)', 'Moldes 2D', '🎄', 'Árbol de Navidad'],
  ['Molde 2D Papanuel', 'Unidad', 'S/ 19.50', 'Moldes 2D', '🎅', 'Papanuel'],
  ['Molde 2D Molde Navideño', 'Unidad', 'S/ 19.50', 'Moldes 2D', '🎄', 'Navideño'],
  ['Molde 2D Maceta Oxagonal', '60 g', 'S/ 19.50', 'Macetas', '🪴', 'Maceta Oxagonal'],
  ['Molde 2D Maceta Cuadrado', '60 g', 'S/ 19.50', 'Macetas', '🪴', 'Maceta Cuadrado'],
  ['Molde 2D Maceta Corazón', '60 g', 'S/ 19.50', 'Macetas', '🪴', 'Maceta Corazón'],
  ['Molde 2D Círculo x 6', 'Unidad', 'S/ 19.50', 'Macetas', '🪴', 'Círculo x 6'],
  ['Molde 2D Maceta Círculo', '60 g', 'S/ 19.50', 'Macetas', '🪴', 'Maceta Círculo'],
  ['Molde 2D Flor de Loto', 'Unidad', 'S/ 38.00', 'Moldes 2D', '🪷', 'Flor de Loto'],
  ['Molde 2D Mano de Buda', '80 g', 'S/ 19.50', 'Moldes 2D', '🪬', 'Mano de Buda'],
  ['Molde 2D Mascotas', 'Unidad', 'S/ 19.50', 'Moldes 2D', '🐶', 'Mascotas'],
  ['Molde 2D Molde Figuras (Aromatizador)', 'Unidad', 'S/ 23.00', 'Moldes 2D', '🌬️', 'Molde Figuras'],
  ['Moldes para Chocolates', 'Unidad / 3 unid.', 'S/ 14.00 / S/ 10.00 c/u', 'Moldes para Chocolates', '🍫', 'Chocolates'],
  ['Moldes para Gomita', 'Unidad / 3 unid.', 'S/ 14.00 / S/ 10.00 c/u', 'Moldes para Gomita', '🍬', 'Gomitas'],

  // NUEVOS PRODUCTOS DEL PDF WHATSAPP — 13/08/2026
  ['Cera de soja', 'Alta fusión · 1 kg', 'S/ 42.00', 'Ceras para velas', '🕯️', 'Soja alta fusión', './assets/nuevos/pdf-page-1.jpg'],
  ['Cera de soja', 'Alta fusión · 500 g', 'S/ 22.00', 'Ceras para velas', '🕯️', 'Soja alta fusión', './assets/nuevos/pdf-page-1.jpg'],
  ['Cera de soja', 'Baja fusión · 1 kg', 'S/ 40.00', 'Ceras para velas', '🕯️', 'Soja baja fusión', './assets/nuevos/pdf-page-2.jpg'],
  ['Cera de soja', 'Baja fusión · 500 g', 'S/ 20.00', 'Ceras para velas', '🕯️', 'Soja baja fusión', './assets/nuevos/pdf-page-2.jpg'],

  ['Fragancia 250 ml · Coco', '250 ml · Mayor desde 3 unidades', 'S/ 48.00 · Mayor S/ 41.00', 'Fragancias 250 ml', '🌸', 'Coco 250 ml', './assets/nuevos/pdf-page-3.jpg'],
  ['Fragancia 250 ml · Jazmín', '250 ml · Mayor desde 3 unidades', 'S/ 48.00 · Mayor S/ 41.00', 'Fragancias 250 ml', '🌸', 'Jazmín 250 ml', './assets/nuevos/pdf-page-3.jpg'],
  ['Fragancia 250 ml · Vainilla', '250 ml · Mayor desde 3 unidades', 'S/ 48.00 · Mayor S/ 41.00', 'Fragancias 250 ml', '🌸', 'Vainilla 250 ml', './assets/nuevos/pdf-page-3.jpg'],
  ['Fragancia 250 ml · Rosas', '250 ml · Mayor desde 3 unidades', 'S/ 48.00 · Mayor S/ 41.00', 'Fragancias 250 ml', '🌸', 'Rosas 250 ml', './assets/nuevos/pdf-page-3.jpg'],
  ['Fragancia 250 ml · Lavanda', '250 ml · Mayor desde 3 unidades', 'S/ 48.00 · Mayor S/ 41.00', 'Fragancias 250 ml', '🌸', 'Lavanda 250 ml', './assets/nuevos/pdf-page-3.jpg'],
  ['Fragancia 250 ml · Eucalipto', '250 ml · Mayor desde 3 unidades', 'S/ 48.00 · Mayor S/ 41.00', 'Fragancias 250 ml', '🌸', 'Eucalipto 250 ml', './assets/nuevos/pdf-page-4.jpg'],
  ['Fragancia 250 ml · Miel', '250 ml · Mayor desde 3 unidades', 'S/ 48.00 · Mayor S/ 41.00', 'Fragancias 250 ml', '🌸', 'Miel 250 ml', './assets/nuevos/pdf-page-4.jpg'],
  ['Fragancia 250 ml · Naranja', '250 ml · Mayor desde 3 unidades', 'S/ 48.00 · Mayor S/ 41.00', 'Fragancias 250 ml', '🌸', 'Naranja 250 ml', './assets/nuevos/pdf-page-4.jpg'],
  ['Fragancia 250 ml · Maracuyá', '250 ml · Mayor desde 3 unidades', 'S/ 48.00 · Mayor S/ 41.00', 'Fragancias 250 ml', '🌸', 'Maracuyá 250 ml', './assets/nuevos/pdf-page-4.jpg'],
  ['Fragancia 250 ml · Uva', '250 ml · Mayor desde 3 unidades', 'S/ 48.00 · Mayor S/ 41.00', 'Fragancias 250 ml', '🌸', 'Uva 250 ml', './assets/nuevos/pdf-page-4.jpg'],

  ['Envase para vela · 250 ml', 'Vidrio ámbar · tapa negra · Mayor desde 6', 'S/ 7.50 c/u', 'Envases para velas', '🫙', 'Envase 250 ml ámbar', './assets/nuevos/pdf-page-5.jpg'],
  ['Envase para vela · 220 ml', 'Colores surtidos · tapa dorada · Mayor desde 6', 'S/ 9.50 c/u', 'Envases para velas', '🫙', 'Envase 220 ml color', './assets/nuevos/pdf-page-6.jpg'],
  ['Envase para vela · 185 ml', 'Vidrio · tapa dorada · Mayor desde 6', 'S/ 10.00 c/u', 'Envases para velas', '🫙', 'Envase 185 ml', './assets/nuevos/pdf-page-7.jpg'],
  ['Envase para vela · 220 ml', 'Vidrio surtido · tapa de madera · Mayor desde 6', 'S/ 9.50 c/u', 'Envases para velas', '🫙', 'Envase 220 ml madera', './assets/nuevos/pdf-page-8.jpg'],
  ['Envase para vela · 150 ml', 'Vidrio ámbar · tapa gris · Mayor desde 6', 'S/ 7.50 c/u', 'Envases para velas', '🫙', 'Envase 150 ml', './assets/nuevos/pdf-page-9.jpg'],
  ['Envase para vela · 315 ml', 'Vidrio transparente · tapa dorada · Mayor desde 6', 'S/ 10.00 c/u', 'Envases para velas', '🫙', 'Envase 315 ml dorado', './assets/nuevos/pdf-page-10.jpg'],
  ['Envase para vela · 350 ml', 'Vidrio · tapa bambú · Mayor desde 6', 'S/ 11.00 c/u', 'Envases para velas', '🫙', 'Envase 350 ml bambú', './assets/nuevos/pdf-page-11.jpg'],
  ['Envase para vela · 210 ml', 'Vidrio con tapa · Mayor desde 6', 'S/ 12.00 c/u', 'Envases para velas', '🫙', 'Envase 210 ml', './assets/nuevos/pdf-page-12.jpg'],
  ['Envase para vela · 250 ml', 'Vidrio decorativo con tapa · Mayor desde 6', 'S/ 10.00 c/u', 'Envases para velas', '🫙', 'Envase 250 ml decorativo', './assets/nuevos/pdf-page-13.jpg'],
  ['Envase para vela · 80 ml', 'Vidrio cuadrado · Mayor desde 6', 'S/ 6.50 c/u', 'Envases para velas', '🫙', 'Envase 80 ml', './assets/nuevos/pdf-page-14.jpg'],
  ['Envase para vela · 100 ml', 'Vidrio ámbar · tapa dorada · Mayor desde 6', 'S/ 6.50 c/u', 'Envases para velas', '🫙', 'Envase 100 ml dorado', './assets/nuevos/pdf-page-15.jpg'],
  ['Envase para vela · 100 ml', 'Vidrio transparente · tapa corcho · Mayor desde 6', 'S/ 6.50 c/u', 'Envases para velas', '🫙', 'Envase 100 ml corcho', './assets/nuevos/pdf-page-16.jpg'],
  ['Envase para vela · 60 ml', 'Vidrio · Mayor desde 6', 'S/ 6.50 c/u', 'Envases para velas', '🫙', 'Envase 60 ml', './assets/nuevos/pdf-page-17.jpg'],
  ['Envase para vela · 100 ml', 'Vidrio transparente · tapa dorada · Mayor desde 6', 'S/ 5.90 c/u', 'Envases para velas', '🫙', 'Envase 100 ml dorado económico', './assets/nuevos/pdf-page-18.jpg'],
  ['Envase para vela · 200 ml', 'Vidrio transparente · tapa dorada · Mayor desde 6', 'S/ 7.00 c/u', 'Envases para velas', '🫙', 'Envase 200 ml', './assets/nuevos/pdf-page-19.jpg'],
  ['Envase para vela · 400 ml', 'Vidrio transparente · tapa dorada · Mayor desde 6', 'S/ 11.00 c/u', 'Envases para velas', '🫙', 'Envase 400 ml', './assets/nuevos/pdf-page-20.jpg'],
  ['Envase para vela · 315 ml', 'Colores surtidos · tapa bambú · Mayor desde 6', 'S/ 10.00 c/u', 'Envases para velas', '🫙', 'Envase 315 ml color', './assets/nuevos/pdf-page-21.jpg']
];
console.log(JSON.stringify(products));