-- Jaboneria Ocean - mejora de catálogo, categorías y estadísticas
-- Ejecutar UNA SOLA VEZ en Supabase SQL Editor.

alter table public.products add column if not exists featured boolean not null default false;
alter table public.products add column if not exists is_offer boolean not null default false;
alter table public.products add column if not exists old_price numeric(12,2);
alter table public.products add column if not exists view_count integer not null default 0;
alter table public.products add column if not exists cart_count integer not null default 0;
alter table public.products add column if not exists sales_count integer not null default 0;

-- Normaliza categorías existentes para evitar duplicados por mayúsculas/espacios.
with ranked as (
  select lower(trim(category)) as k,
         trim(regexp_replace(category, '\\s+', ' ', 'g')) as canonical,
         count(*) as n,
         row_number() over (partition by lower(trim(category)) order by count(*) desc, trim(regexp_replace(category, '\\s+', ' ', 'g'))) as rn
  from public.products
  where category is not null and trim(category) <> ''
  group by lower(trim(category)), trim(regexp_replace(category, '\\s+', ' ', 'g'))
), canon as (
  select k, canonical from ranked where rn=1
)
update public.products p
set category = canon.canonical
from canon
where lower(trim(p.category)) = canon.k
  and p.category is distinct from canon.canonical;

create table if not exists public.store_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  product_id uuid references public.products(id) on delete set null,
  query text,
  created_at timestamptz not null default now()
);

create index if not exists store_events_type_idx on public.store_events(event_type);
create index if not exists store_events_product_idx on public.store_events(product_id);
create index if not exists store_events_created_idx on public.store_events(created_at desc);

alter table public.store_events enable row level security;

drop policy if exists "store_events_admin_read" on public.store_events;
create policy "store_events_admin_read"
on public.store_events
for select to authenticated
using (public.is_admin());

create or replace function public.log_store_event(
  p_event_type text,
  p_product_id uuid default null,
  p_query text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_event_type not in ('page_view','product_view','add_to_cart','whatsapp_click','search') then
    return;
  end if;
  insert into public.store_events(event_type, product_id, query)
  values (p_event_type, p_product_id, left(nullif(trim(p_query),''), 120));

  if p_event_type = 'product_view' and p_product_id is not null then
    update public.products set view_count = view_count + 1 where id = p_product_id;
  elsif p_event_type = 'add_to_cart' and p_product_id is not null then
    update public.products set cart_count = cart_count + 1 where id = p_product_id;
  end if;
end;
$$;

grant execute on function public.log_store_event(text, uuid, text) to anon, authenticated;
grant select on public.store_events to authenticated;

-- Permisos para las nuevas columnas siguen las políticas existentes de products.
grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
